### ISSUE TITLE
不反思为啥资源分配不均,以前拿临时工开刀，现在对实习生下手，字节高管吃香难看

### ISSUE THREAD

**Issue by monglebest** [JusticeFighterDance/JusticeFighter110#17]
明明是高管自己偏袒部分团队，没管理好队伍，导致资源不平衡，部分人得不到重用，记狠在心。全职员工都是软柿子不敢反抗，就一个实习生跳出来搞事情。还这么大摇大摆的要在github上面全网曝光，不知道丢谁的脸。

好奇有几个人懂hugingface攻击? 

当的了受气包的恼种们是不会反抗的.

**Comment by GoatGirl98** [comment]
那跟主管或者更高层爆了的方法有的是啊，对集群下手反而是让做实验的同事遭殃啊（甚至可能会殃及不构成竞争关系的人）。搞不同团队赛马的是高层，结果最后搞成了底层互害是不是有点太幽默了？

不过当事人据我所知目前应该没啥事，字节方面澄清他不在ai lab实习之后就把linkin主页的ai lab部分去掉了，但是个人简介的“勿信谣勿传谣”没有删。他也有可能会再准备爆一些其他料。且观望吧，也许事情后续的走向会如你所愿呢？

**Comment by cxy1997** [comment]
> 明明是高管自己偏袒部分团队，没管理好队伍，导致资源不平衡，部分人得不到重用，记狠在心。全职员工都是软柿子不敢反抗，就一个实习生跳出来搞事情。还这么大摇大摆的要在github上面全网曝光，不知道丢谁的脸。
> 
> 好奇有几个人懂hugingface攻击?
> 
> 当的了受气包的恼种们是不会反抗的.

没活了可以咬打火机

**Comment by monglebest** [comment]
> 是有点太幽

被惩罚也是高层对你们做的事，本来就只是跟这个实习生有关，偏要因为连你们也一起惩罚了。在github发这个帖子才真叫一群人让一个人去死。这不是所谓正义，是一群人对一个没有权利的实习生的霸凌abuse. 人家还没进社会，就想让人家社死,这是何据心? 有没有想过，万一这哥们破罐子破摔，到时候跟踪你们谁，然后杀人灭口？人家既然报复心那么强,你们要是没有能力把他送进监狱，又在外面乱叫。你们自己小心点才是。

**Comment by cxy1997** [comment]
> > 是有点太幽
> 
> 被惩罚也是高层对你们做的事，本来就只是跟这个实习生有关，偏要因为连你们也一起惩罚了。在github发这个帖子才真叫一群人让一个人去死。这不是所谓正义，是一群人对一个没有权利的实习生的霸凌abuse. 人家还没进社会，就想让人家社死,这是何据心? 有没有想过，万一这哥们破罐子破摔，到时候跟踪你们谁，然后杀人灭口？人家既然报复心那么强,你们要是没有能力把他送进监狱，又在外面乱叫。你们自己小心点才是。

笑死，杀人灭口都出来了，留个档

**Comment by GoatGirl98** [comment]
> > 是有点太幽
> 
> 被惩罚也是高层对你们做的事，本来就只是跟这个实习生有关，偏要因为连你们也一起惩罚了。在github发这个帖子才真叫一群人让一个人去死。这不是所谓正义，是一群人对一个没有权利的实习生的霸凌abuse. 人家还没进社会，就想让人家社死,这是何据心? 有没有想过，万一这哥们破罐子破摔，到时候跟踪你们谁，然后杀人灭口？人家既然报复心那么强,你们要是没有能力把他送进监狱，又在外面乱叫。你们自己小心点才是。

我知道你很急，但是你先别急。我不是说的当事人大概率不会善罢甘休吗？没必要搁这虚空打靶对着不可名状之物输出一堆。你没法提供什么有力证据的话等着看好戏就完事了

**Comment by willowdong** [comment]
你小号怎么这么多

**Comment by Alan33668899** [comment]
> > > 是有点太幽
> > 
> > 
> > 被惩罚也是高层对你们做的事，本来就只是跟这个实习生有关，偏要因为连你们也一起惩罚了。在github发这个帖子才真叫一群人让一个人去死。这不是所谓正义，是一群人对一个没有权利的实习生的霸凌abuse. 人家还没进社会，就想让人家社死,这是何据心? 有没有想过，万一这哥们破罐子破摔，到时候跟踪你们谁，然后杀人灭口？人家既然报复心那么强,你们要是没有能力把他送进监狱，又在外面乱叫。你们自己小心点才是。
> 
> 我知道你很急，但是你先别急。我不是说的当事人大概率不会善罢甘休吗？没必要搁这虚空打靶对着不可名状之物输出一堆。你没法提供什么有力证据的话等着看好戏就完事了

以你对当事人的了解，他后续还会继续爆料和搞事情嘛

**Comment by eggegyptians** [comment]
> > 明明是高管自己偏袒部分团队，没管理好队伍，导致资源不平衡，部分人得不到重用，记狠在心。全职员工都是软柿子不敢反抗，就一个实习生跳出来搞事情。还这么大摇大摆的要在github上面全网曝光，不知道丢谁的脸。 好奇有几个人懂hugingface攻击? 当的了受气包的恼种们是不会反抗的.

> 被惩罚也是高层对你们做的事，本来就只是跟这个实习生有关，偏要因为连你们也一起惩罚了。在github发这个帖子才真叫一群人让一个人去死。这不是所谓正义，是一群人对一个没有权利的实习生的霸凌abuse. 人家还没进社会，就想让人家社死,这是何据心? 有没有想过，万一这哥们破罐子破摔，到时候跟踪你们谁，然后杀人灭口？人家既然报复心那么强,你们要是没有能力把他送进监狱，又在外面乱叫。你们自己小心点才是。

疑似tky的另一个小号在继续无证据的传播谣言。

0. ‘明明是高管自己偏袒部分团队’: 避重就轻，不提自己做了攻击，还是潜意识认为错出在高管资源分布不平衡，并且透露了更多的信息，小号这个人主观认为是‘高管自己偏袒部分团队’，不重用你就是有错，没管理好。
1. ‘全职员工都是软柿子不敢反抗’: 6。
2. ‘大摇大摆的要在github上面全网曝光，不知道丢谁的脸’: 潜意识认为曝光内容属实，主要是丢脸。
3. ‘被惩罚也是高层对你们做的事，本来就只是跟这个实习生有关’:在回应另一个人的回答中，透露出更多的细节内容，为“字节内部因为这个实习生，高层惩罚了更多其他的人”。显然作为一个新注册的小号，即一定是字节内部人员。在另一个人的发言中描述的是“对集群下手反而是让做实验的同事遭殃啊”，指的是hf攻击，但是在该号回复被理解为“高层惩罚了别人”并继续输出。
4. ‘万一这哥们破罐子破摔，到时候跟踪你们谁，然后杀人灭口？’: 6，存档。
5. '你们要是没有能力把他送进监狱，又在外面乱叫': 恼羞成怒，有种巴不得tky进局子的美感。
6. ‘你们自己小心点才是’: 可以理解为赤裸裸的威胁。

正如疑似的另一个小号发的[repo](https://github.com/william-sto/JusticeNeverTooLate)说所谓的"**内部人员... 正义会迟到但不会缺席... 提供所有依据...**", 后续什么证据都没有，只有主观情绪煽动。

希望能拿出更多的证据，而不是说完后输出完后关掉issue，也可以发到简中互联网，如知乎等，让大家都小心下～

**Comment by monglebest** [comment]
> > > 明明是高管自己偏袒部分团队，没管理好队伍，导致资源不平衡，部分人得不到重用，记狠在心。全职员工都是软柿子不敢反抗，就一个实习生跳出来搞事情。还这么大摇大摆的要在github上面全网曝光，不知道丢谁的脸。 好奇有几个人懂hugingface攻击? 当的了受气包的恼种们是不会反抗的.
> 
> > 被惩罚也是高层对你们做的事，本来就只是跟这个实习生有关，偏要因为连你们也一起惩罚了。在github发这个帖子才真叫一群人让一个人去死。这不是所谓正义，是一群人对一个没有权利的实习生的霸凌abuse. 人家还没进社会，就想让人家社死,这是何据心? 有没有想过，万一这哥们破罐子破摔，到时候跟踪你们谁，然后杀人灭口？人家既然报复心那么强,你们要是没有能力把他送进监狱，又在外面乱叫。你们自己小心点才是。
> 
> 疑似tky的另一个小号在继续无证据的传播谣言。
> 
> 0. ‘明明是高管自己偏袒部分团队’: 避重就轻，不提自己做了攻击，还是潜意识认为错出在高管资源分布不平衡，并且透露了更多的信息，小号这个人主观认为是‘高管自己偏袒部分团队’，不重用你就是有错，没管理好。
> 1. ‘全职员工都是软柿子不敢反抗...当的了受气包的恼种们是不会反抗的’: 6。
> 2. ‘大摇大摆的要在github上面全网曝光，不知道丢谁的脸’: 潜意识认为曝光内容属实，主要是丢脸。
> 3. ‘被惩罚也是高层对你们做的事，本来就只是跟这个实习生有关’:在回应另一个人的回答中，透露出更多的细节内容，为“字节内部因为这个实习生，高层惩罚了更多其他的人”。显然作为一个新注册的小号，即一定是字节内部人员。在另一个人的发言中描述的是“对集群下手反而是让做实验的同事遭殃啊”，指的是hf攻击，但是在该号回复被理解为“高层惩罚了别人”并继续输出。
> 4. ‘万一这哥们破罐子破摔，到时候跟踪你们谁，然后杀人灭口？’: 6，存档。
> 5. '你们要是没有能力把他送进监狱，又在外面乱叫': 恼羞成怒，有种巴不得tky进局子的美感。
> 6. ‘你们自己小心点才是’: 可以理解为赤裸裸的威胁。
> 
> 正如疑似的另一个小号发的[repo](https://github.com/william-sto/JusticeNeverTooLate)说所谓的"**内部人员... 正义会迟到但不会缺席... 提供所有依据...**", 后续什么证据都没有，只有主观情绪煽动。
> 
> 希望能拿出更多的证据，而不是说完后输出完后关掉issue，也可以发到简中互联网，如知乎等，让大家都小心下～

你是今天没吃药嘛? 还是有被迫害妄想? 以为所有人都跟你bytedance一样想的吗? 皇帝的新衣是不是穿傻了。我想关就关，关你什么事!
![IMG_1660](https://github.com/user-attachments/assets/dd999607-2db1-4784-ba28-086a375704a9)
