### ISSUE TITLE
好奇字节对应组的不同人权限划分问题

### ISSUE THREAD

**Issue by Maxpicca-Li** [JusticeFighterDance/JusticeFighter110#29]
这种级别的实验，为什么一个人有权限修改共享数据、他人数据，甚至有权限 kill 他人进程呢？
```
1 修改集群pytorch源码，包括随机种子，优化器，数据加载
2 随机kill 多机实验进程，导致大卡实验卡死
3 通过checkpoint打开登陆后门，自动发起攻击随机停止进程
4 参加集群故障排查日会，根据同事排查思路持续定向修改攻击代码
5 修改同事模型权重，造成实验结果无法复现
```

**Comment by Drincann** [comment]
注入攻击，从来都不需要攻击者真正拥有攻击目标的权限，只要加载了恶意代码的环境有权限就够了。

**Comment by Maxpicca-Li** [comment]
> 注入攻击，从来都不需要攻击者真正拥有攻击目标的权限，只要加载了恶意代码的环境有权限就够了。

是这样的。但我这里是指，环境所加载的代码，应该放在共享区，而共享区，一般人只有查看权限，没有修改权限。

**Comment by Maxpicca-Li** [comment]
> > 是这样的。但我这里是指，环境所加载的代码，应该放在共享区，而共享区，一般人只有查看权限，没有修改权限。
> 
> 没太理解你说的共享区具体是什么东西，他是利用反序列化漏洞来加载恶意代码的，只需要把模型传上去，等别人用就好了。

😂好吧。简单来说，不管是修改代码，还是修改模型，理论上田某都不应该被赋予“修改”的权限，除非他自己使用。节子自身权限还是需要优化。
