### ISSUE TITLE
这段录音的真实性有待商榷？

### ISSUE THREAD

**Issue by steve-zeyu-zhang** [JusticeFighterDance/JusticeFighter110#3]
事情的经过虽然是道听途说的，但是很令人既震撼又诧异.

@keyu-tian 的工作一直以来在research上都给我带来很大的inspiration. 虽然我没有机会和他交流过但是从他的工作而言能看出他对research充满热情. 我也一直期待有机会能和他交流.

很难想象这么优秀的rising star会为了发泄某些不满而去自毁前程. 我对这段录音的真实性表示怀疑的态度.

希望字节官方能还原真相, 我们都期待着一个positive的结果

**Comment by GoatGirl98** [comment]
我身边有和他很熟的同学听过录音了，基本上可以确认声音是他的没有错。作为他的本科同学，我们不少人一开始也很难相信他干得出这种事情。

**Comment by william-sto** [comment]
@GoatGirl98 @steve-zeyu-zhang @crj1998 @Alan33668899 @BRsjtu @wondervictor @ax7e @Rocky12138 音频是可以伪造的。要是你待过字节，就会知道如果真的审查音频是不可能泄露的。这和犯罪没什么两样。且无任何辩解可能。

此外有太多内容不符事实。建议转到  https://github.com/william-sto/JusticeNeverTooLate

**Comment by Alan33668899** [comment]
> @GoatGirl98 @steve-zeyu-zhang @crj1998 @Alan33668899 @BRsjtu @wondervictor @ax7e @Rocky12138 音频是可以伪造的。要是你待过字节，就会知道如果真的审查音频是不可能泄露的。这和犯罪没什么两样。且无任何辩解可能。
> 
> 此外有太多内容不符事实。建议转到 https://github.com/william-sto/JusticeNeverTooLate

看一看先哈

**Comment by Wloner0809** [comment]
> 事情的经过虽然是道听途说的，但是很令人既震撼又诧异.
> 
> tky的工作一直以来在research上都给我带来很大的inspiration. 虽然我没有机会和他交流过但是从他的工作而言能看出他对research充满热情. 我也一直期待有机会能和他交流.
> 
> 很难想象这么优秀的rising star会为了发泄某些不满而去自毁前程. 我对这段录音的真实性表示怀疑的态度.
> 
> 希望字节官方能还原真相, 我们都期待着一个positive的结果

你这跟追星的脑残粉的脑回路差不多, 从你的话中可以推断出对research很有热情的人不会为了发泄某些不满而去伤害别人, 这显然没有一点逻辑的。当然, 让子弹再飞一会是对的

**Comment by weite8** [comment]
毫无逻辑，有热情和祸害他人不冲突

**Comment by steve-zeyu-zhang** [comment]
感到很惋惜😞

![1000011062](https://github.com/user-attachments/assets/94d11826-75f7-4dda-9119-62fb73789eb8)
