### ISSUE TITLE
字节的安全搞得真是太挫了

### ISSUE THREAD

**Issue by qinkunbao** [JusticeFighterDance/JusticeFighter110#7]
虽然实习生的行为有待商榷，但是整个事件听起来有点匪夷所思啊

> 1 修改集群pytorch源码，包括随机种子，优化器，数据加载

你们不code review吗

> 2 随机kill 多机实验进程，导致大卡实验卡死

所有机器都可以ssh吗

> 3 通过checkpoint打开登陆后门，自动发起攻击随机停止进程

为啥会有后门，用户的数据是不是也可以后门查看

> 4 参加集群故障排查日会，根据同事排查思路持续定向修改攻击代码

这个如果是真的，的确不太好

> 5 修改同事模型权重，造成实验结果无法复现

无法理解为啥一个实习生可以改其他人模型的参数

**Comment by WuSiYu** [comment]
纯路人，仅从技术角度分析

1. 可能是改的一个公用的conda环境里的torch代码
2. 用过一些大厂的k8s容器化训练平台，如果你有权限，确实可以进入任务中的任意容器
3. pickle格式的checkpoint并不安全（因为这东西pickle只是python的对象序列化工具），可以注入任意代码（解决方案是用safetensors）但一般内部也不会有人想到还需要防自己人
4. 《社 会 工 程 学》
5. 可能是很多人共用一个存储池之类的东西

**Comment by william-sto** [comment]
@qinkunbao 大量事实不符。见https://github.com/william-sto/JusticeNeverTooLate

**Comment by MagicGopher** [comment]
实习生的权限这么大的吗？代码不需要review？

**Comment by caradryanl** [comment]
有可能训练代码没有任何问题，是通过huggingface自己的漏洞注入错的配置文件进行攻击的

**Comment by ducatiqwq** [comment]
@william-sto 拿不出证据来就不要东扯西扯。一个仓库放了录音连接，另一个自己口嗨，你说我信哪一个？
